"use client"

import { useHeader } from "@/context/HeaderContext";
import { useEffect } from "react";

export default function PrivacyPolicyComponent() {
  const basePath = process.env.NEXT_PUBLIC_PATH;

  const { setHeaderProps } = useHeader()

  useEffect(() => {
      setHeaderProps({})
  }, [])

  return (
    <main className="w-full pt-40" style={{backgroundImage: `url(${basePath}images/home/bg-pattern.png)`}}>
      <div className="px-5 lg:px-15 xl:px-20 2xl:px-30 py-10 flex flex-col gap-5">
        <h1 className="text-4xl font-georgia">Privacy Policy</h1>
        <p>In the course of using this website or availing the services offered on the website vide the online application forms, communication services etc., N. L. Dalmia Institute of Management Studies and Research (“the Company” or “N. L. Dalmia Institute of Management Studies and Research”) and its Affiliates may become privy to the personal information of the users, including information that is of a confidential nature.</p>
        <p>We know that you care how information about you is used and shared, and we appreciate your trust that we will do so carefully and sensibly. We are strongly committed to protecting your privacy and have taken all necessary and reasonable measures to protect the confidentiality of your information and its transmission through the world wide web and the Company shall not be held liable for disclosure of the confidential information when in accordance with this Privacy Policy as may be amended from time to time by the Company or in terms of the agreements, if any, with the Customers or visitors of this website. This Privacy Policy describes how we handle your personal information for our services on this website.</p>
        <h2 className="text-2xl font-georgia">Acceptance of this Policy</h2>
        <p>By visiting www.nldalmia.in(the website), you are accepting the practices and the terms and conditions described in this Privacy Policy. We may amend this policy at any time by posting a revised version on our website. The revised version will be effective from the time we post it.</p>
        <h2 className="text-2xl font-georgia">What Personal Information N. L. Dalmia Institute of Management Studies and Research Gathers & Why?</h2>
        <p>You can browse our site without telling us who you are or revealing any personal information about yourself. Once you give us your personal information, you are not anonymous to us. If you choose to provide us with personal information, you consent to the transfer and storage of that information on our servers and use of your personal information as mentioned in the Privacy Policy.</p>
        <p>The information we learn from you helps us personalize and continually improve your online experience at the website. Here are the types of information we gather:</p>
        <ul className="list-outside list-disc lg:pl-5 flex flex-col gap-2">
          <li>Information You Give Us: We receive and store any information you enter on the website or give us in any other way. You can choose not to provide certain information; in such an event you might not be able to take advantage of many of our features. We use the information that you provide us for such purposes as responding to your requests, customizing the site for you, improving our site, and communicating with you.</li>
          <li>Automatic Information: We receive and store certain types of information whenever you interact with us. For example, like many other websites, we use “cookies,” and we obtain certain types of information when your Web browser accesses our website.</li>
          <li>E-mail Communications: To help us make e-mails more useful and interesting, we often receive a confirmation when you open e-mail sent from the website, if your computer supports such capabilities. We may also compare our customer list to lists received from other companies, in an effort to avoid sending unnecessary messages to our customers.</li>
          <li>Information from Other Sources: We might receive information about you from other sources and add it to our account information.</li>
        </ul>
        <h2 className="text-2xl font-georgia">Cookies from the website:</h2>
        <p>Cookies are alphanumeric identifiers that we may transfer to your computer’s hard drive through your Web browser to enable our systems to recognize your browser and to provide special features and to save other settings. The Help portion of the toolbar on most browsers will tell you how to prevent your browser from accepting new cookies, how to have the browser notify you when you receive a new cookie, or how to disable cookies altogether. Additionally, you can disable or delete similar data used by browser add-ons, such as Flash cookies, by changing the add-on’s settings or visiting the Website of its manufacturer. However, because cookies allow you to take advantage of some essential features, we recommend that you leave them turned on. For instance, if you block or otherwise reject our cookies, you will not be able to use services that require you to Sign in.</p>
        <h2 className="text-2xl font-georgia">Does N. L. Dalmia Institute of Management Studies and Research Share the Information It Receives?</h2>
        <p>When you voluntarily send us electronic mail, we will keep a record of this information so that we can respond to you. We only collect information from you when you register on our site or fill out a form. Also, when filling out a form on our site, you may be asked to enter your: name, e-mail address, or phone number. You may, however, visit our site anonymously. In case you have submitted your personal information and contact details, we reserve the right to Call, SMS, Email, or WhatsApp about our products and offers, even if your number has DND activated on it.</p>
        <p>We do not sell or rent your personal information to third parties for their marketing purposes without your explicit consent. We may combine your information with information we collect from other companies and use it to improve and personalize our services, content, and advertising. If you do not wish to receive marketing communications from us or participate in our ad-customization programs, simply indicate your preference once you sign-on in this website or by following the directions provided in an email or from a link on the advertisement. Information about our customers is an important part of our business, and we are not in the business of selling it to others. We share customer information only as described in the Privacy Policy:</p>
        <ol className="list-decimal lg:pl-5 flex flex-col gap-2">
          <li>Third-Party Service Providers: We may employ other companies and individuals to perform functions on our behalf. Examples include sending postal mails or e-mails, removing repetitive information from customer lists, analyzing data, providing marketing assistance, providing search results and links (including paid listings and links), providing customer service, etc. They have access to personal information needed to perform their functions, but will not use it for other purposes.</li>
          <li>Promotional Offers: Sometimes we may send offers to selected groups of the Company’s customers on behalf of other parties. When we do this, we do not give that party your name and address.</li>
          <li>Business Transfers: As we continue to develop our business, we might sell or buy stores, subsidiaries, or business units. In such transactions, customer information generally is one of the transferred business assets but remains subject to the promises made in any pre-existing Privacy Policy.</li>
          <li>Protection of the Company and Others: We release account and other personal information when we believe release is appropriate or mandatory to comply with the law; enforce or apply our Conditions of Use and other agreements; or protect the rights, property, or safety of the Company, our users, or others. This includes exchanging information with other companies and organizations for fraud protection and credit risk reduction. However, this does not include selling, renting, sharing, or otherwise disclosing personally identifiable information from customers for commercial purposes in violation of the commitments set forth in this Privacy Notice.</li>
          <li>With Your Consent: Other than as set out above, you will receive notice when information about you might go to third parties, and you will have an opportunity to choose not to share the information.</li>
        </ol>
        <h2 className="text-2xl font-georgia">Third-party advertisers and Links to Other Websites</h2>
        <p>Our site includes third-party advertising and links to other websites. We do not provide any personally identifiable customer information to these advertisers or third-party websites. Click here for some examples as well as information on how to contact these companies to learn more or opt-out of their information collection practices. These third-party websites and advertisers, or Internet advertising companies working on their behalf, sometimes use technology to send (or “serve”) the advertisements that appear on our website directly to your browser. They automatically receive your IP address when this happens. They may also use cookies, JavaScript, web beacons (also known as action tags or single-pixel gifs), and other technologies to measure the effectiveness of their ads and to personalize advertising content. We do not have access to or control over cookies or other features that they may use, and the information practices of these advertisers and third-party websites are not covered by this Privacy Notice. Please contact them directly for more information about their privacy practices.</p>
        <h2 className="text-2xl font-georgia">Which Information Can I Access?</h2>
        <p>The site gives you access to a broad range of information about your account and your interactions on the site for the limited purpose of viewing and, in certain cases, updating that information. You must promptly update your personal information if it changes or is inaccurate.</p>
        <h2 className="text-2xl font-georgia">What Choices Do I Have?</h2>
        <p>As referred above, you can always choose not to provide information. You can add or update certain information on certain pages. If you do not want to receive e-mails or other mails from us, please adjust your Customer Communication Preferences. (If you do not want to receive Conditions of Use and other legal notices from us, such as this Privacy Notice, those notices will still govern your use of the site, and it is your responsibility to review them for changes.)</p>
        <h2 className="text-2xl font-georgia">Activities Associated with User IDs</h2>
        <p>Your User ID is displayed throughout the website and is therefore available to the public. All of your activities on our sites is traceable to your User ID. Notices are sent to other community members regarding suspicious activity and policy violations on our sites and refer to User IDs and specific items. Therefore, if you associate your name with your User ID, the people to whom you have revealed your name will be able to personally identify your activities on the site.</p>
        <h2 className="text-2xl font-georgia">Account Protection</h2>
        <p>Your password is the key to your account. To make the password complex and difficult for others to guess, you should use a combination of alphabets, numbers, and special characters like, !, @, #, $, etc., and do not disclose your password to any person. If you do share your password or your personal information with others, remember that you are responsible for all actions taken in the name of your account. If you lose control of your password, you may lose substantial control over your personal information and may be subject to legally binding actions taken on your behalf. Therefore, if your password has been compromised for any reason, you should immediately notify the Company and change your password.</p>
        <h2 className="text-2xl font-georgia">No Spam, Spyware or Spoofing</h2>
        <p>We and our users do not tolerate spam. Make sure to set notification preferences of the website so we communicate to you as you prefer. You are not licensed to add other site users to your mailing list (email or physical mail) without their express consent. You may not use our communication tools to send spam or otherwise send content that would violate our User Agreement. We automatically scan and may manually filter messages to check for spam, viruses, phishing attacks, and other malicious activity or illegal or prohibited content, but we do not permanently store messages sent through these tools. If you send an email to an email address that is not registered in our community, we do not permanently store that email or use that email address for any marketing purpose. We do not rent or sell these email addresses.</p>
        <h2 className="text-2xl font-georgia">Are Children Allowed to Use the site?</h2>
        <p>Only persons in the age group of 18 years and above can use our website. If you are below 18 years of age, you shall not use our website. However, if you still desire to do so, you may do it only under the guidance of a parent or guardian. We do not collect information from children but have no control over persons below the age of 18 years who leave information through this website with false details.</p>
        <h2 className="text-2xl font-georgia">Other Information</h2>
        <p>The transmission of data over the internet is not guaranteed to be completely secure. It may be possible for third parties not under the control of www.nldalmia.into intercept or access transmissions or private communications unlawfully. While we strive to protect your Personal Information, neither www.nldalmia.in nor any of our service providers can ensure or warrant the security of any information you transmit to us over the internet. Any such transmission is done at your own risk. N. L. Dalmia Institute of Management Studies and Research Reserves the right to amend the specifications, colours, and dimensions of any product without prior notice. Colour deviation may occur due to different screen resolutions used by the user.</p>
        <h2 className="text-2xl font-georgia">Intellectual Property Rights</h2>
        <p>The entire website including its content, such as text, graphics, logos, icons, images, audio clips, video clips, software or other intellectual property rights, is the property of the Company or its content suppliers and protected by Indian copyright and intellectual property laws.</p>
        <p>The compilation (meaning the collection, arrangement and assembly) of all content on the Website is the exclusive property of the Company and protected by Indian copyright laws.</p>
        <p>All software used on the website is the property of the Company or its software suppliers and protected by Indian copyright and intellectual property laws. Permission is granted to electronically copy and print hard copy portions of the Website for the sole purpose of placing an order on the Website or using the Website as a shopping resource. Any other use, including the reproduction, modification, distribution, transmission, republication, display or performance, of the content of the Website is strictly prohibited.</p>
        <p>At N. L. Dalmia Institute of Management Studies and Research, we value your relationship and will at all times strive to ensure your privacy.</p>
      </div>
    </main>
  );
}